### ISSUE TITLE
Discourse staging redirects improperly from http

### ISSUE THREAD

**Issue by rleitan** [mozilla-it/discourse-infra#31]
[Environment]:
iOS 12.4 - Safari, Firefox

[STR]:
1.Open https://discourse-staging.itsre-apps.mozit.cloud

[Expected result]:
The page should be loaded

[Actual result]:
Blank page

The network connection was lost message is displayed

**Comment by LeoMcA** [comment]
I don't think the issue here is iOS, but loading `http://discourse-staging.itsre-apps.mozit.cloud`. Specifically http rather than https.

If I specify https on iOS, it works for me.

If you open a Firefox private window you'll see the same behaviour.

**Comment by the-smooth-operator** [comment]
I can reproduce it. Will look into it, thanks!

**Comment by LeoMcA** [comment]
Fix deployed, works for me. @rleitan can you confirm?
