### ISSUE TITLE
Uploading pictures of more than 1MB returns 413 in console and no error message to the user

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-it/discourse-infra#33]
**STR:**
1. Login to [discourse](https://discourse-staging.itsre-apps.mozit.cloud)
2. Navigate to Preferences - Profile [page](https://discourse-staging.itsre-apps.mozit.cloud/u/viorela/preferences/profile)
3. Upload a picture of more than 1MB in the Profile background or User card background sections

**Expected:**
Picture upload works, as the size limit is set to 4096KB

**Actual:**
Picture is not uploaded, no error message displayed to the user. See [video](https://drive.google.com/file/d/1R_dh8IfOK_jPVfpiKI5t28cUIdYN4uiM/view?usp=sharing)
Error is shown in browser console: "_Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)"_

**Note:**
I also received an error message when trying to upload a picture of 2.5MB:
_"Sorry, that file is too big (maximum size is 4096kb). Why not upload your large file to a cloud sharing service, then paste the link?"_

**Comment by the-smooth-operator** [comment]
Thanks @viorelaioia for finding this.

The problem with the upload not being processed is that the ingress controller (NGINX) is blocking the uploads of files bigger than 1MB. 
This value is easy to change, I've set it up 4 MB in "dev" environment and after that I can upload pictures up to 4MB of size as expected.
However when trying to upload a 5MB picture, the upload is not successful and I don't get any error message.

@LeoMcA what's the maximum allowed upload size that I should set? 4MB sounds reasonable, but I want to make sure this is in line with Discourse.
Also, do you have any idea about why we don't get an error message? It could easily be that the feature was never implemented...

**Comment by LeoMcA** [comment]
> @LeoMcA what's the maximum allowed upload size that I should set? 4MB sounds reasonable, but I want to make sure this is in line with Discourse.

4MiB is the default in Discourse, so that should be fine. We can always up it in future if we run into problems.

> Also, do you have any idea about why we don't get an error message? It could easily be that the feature was never implemented...

I'm not sure, nginx doesn't seem to return a status code when the request body is too large... it just kills the connection. If it were to return a 413 then Discourse might display an error.

**Comment by the-smooth-operator** [comment]
Thanks @LeoMcA I'll set the max body size to 4MB.

Regarding NGINX not returning 413, based on the docs, after this setting is enabled, it should throw it. https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size

**Comment by the-smooth-operator** [comment]
Currently a user can upload pictures up to 4MB large. However when trying to upload a bigger file, the upload will fail and the user won't be notified.
This behavior is also appearing in current production, so we won't tackle it now.
