### ISSUE TITLE
[mobile] Cannot upload recently taken photo

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-it/discourse-infra#37]
**Env:**
android P, latest Firefox and Chrome
iOS 12.4, latest Firefox

**STR:**

1. Login to discourse
2. Tap the button to add a new post
3. Enter a title for the topic and select a category
4. Tap the Photo upload button 
5. Select Camera
6. Take a picture and confirm you want to upload it

**Expected :**
Photo is uploaded, it is displayed in topic preview

**Actual:**
Photo is not uploaded, it is not displayed in topic preview. See [vide](https://drive.google.com/file/d/1eobltDiM_6H9-xeMIlPgXL-iFmJ4GGfY/view?usp=sharing)

**Note:**
Uploading a photo from Gallery works as expected.

**Comment by LeoMcA** [comment]
This looks like the error which happens when too large an image is uploaded...

@viorelaioia can you confirm how large the image that you attempted to upload is/how large a typical image from your phone camera is (if you can't find the size of that one in particular)

**Comment by viorelaioia-zz** [comment]
@LeoMcA , the picture has a size of 2.4 MB

**Comment by viorelaioia-zz** [comment]
This issue is not reproducible anymore.
